## This is basic continuous integration build for your Quarkus application.

name: Synantisi Maven Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build
        run: ./mvnw verify -B
  #gpt-code-review-action for PR check provided by AI
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: sshnaidm/gpt-code-review-action@v1.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}